export const OPEN_AUTH_FORM = 'OPEN_AUTH_FORM'
export const CLOSE_AUTH_FORM = 'CLOSE_AUTH_FORM'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const RESTORE_REQUEST = 'RESTORE_REQUEST'
export const RESTORE_SUCCESS = 'RESTORE_SUCCESS'
export const RESTORE_FAILURE = 'RESTORE_FAILURE'

export const LOGIN_NEW_PASSWORD_REQUEST = 'LOGIN_NEW_PASSWORD_REQUEST'
export const LOGIN_NEW_PASSWORD_SUCCESS = 'LOGIN_NEW_PASSWORD_SUCCESS'
export const LOGIN_NEW_PASSWORD_FAILURE = 'LOGIN_NEW_PASSWORD_FAILURE'

export const VERIFY_ACCOUNT_REQUEST = 'VERIFY_ACCOUNT_REQUEST'
export const VERIFY_ACCOUNT_SUCCESS = 'VERIFY_ACCOUNT_SUCCESS'
export const VERIFY_ACCOUNT_FAILURE = 'VERIFY_ACCOUNT_FAILURE'

export const RENEW_TOKEN_REQUEST = 'RENEW_TOKEN_REQUEST'
export const RENEW_TOKEN_SUCCESS = 'RENEW_TOKEN_SUCCESS'
export const RENEW_TOKEN_FAILURE = 'RENEW_TOKEN_FAILURE'

export const UPDATE_PROFILE_INFO_REQUEST = 'UPDATE_PROFILE_INFO_REQUEST'
export const UPDATE_PROFILE_INFO_SUCCESS = 'UPDATE_PROFILE_INFO_SUCCESS'
export const UPDATE_PROFILE_INFO_FAILURE = 'UPDATE_PROFILE_INFO_FAILURE'

export const UPDATE_PROFILE_PASSWORD_REQUEST = 'UPDATE_PROFILE_PASSWORD_REQUEST'
export const UPDATE_PROFILE_PASSWORD_SUCCESS = 'UPDATE_PROFILE_PASSWORD_SUCCESS'
export const UPDATE_PROFILE_PASSWORD_FAILURE = 'UPDATE_PROFILE_PASSWORD_FAILURE'

export const TOKEN_NAME = 'AlphaKastaToken'
export const TOKEN_SECRET_NAME = 'AlphaKastaAccessToken'
