export const GET_BETS_REQUEST = 'GET_BETS_REQUEST'
export const GET_BETS_SUCCESS = 'GET_BETS_SUCCESS'
export const GET_BETS_FAILURE = 'GET_BETS_FAILURE'

export const CREATE_BET_REQUEST = 'CREATE_BET_REQUEST'
export const CREATE_BET_SUCCESS = 'CREATE_BET_SUCCESS'
export const CREATE_BET_FAILURE = 'CREATE_BET_FAILURE'

export const JOIN_BET_REQUEST = 'JOIN_BET_REQUEST'
export const JOIN_BET_SUCCESS = 'JOIN_BET_SUCCESS'
export const JOIN_BET_FAILURE = 'JOIN_BET_FAILURE'

export const CLOSE_BET_REQUEST = 'CLOSE_BET_REQUEST'
export const CLOSE_BET_SUCCESS = 'CLOSE_BET_SUCCESS'
export const CLOSE_BET_FAILURE = 'CLOSE_BET_FAILURE'
